actions

diff --git a/.github/workflows/swift.yml b/.github/workflows/swift.yml
--- a/.github/workflows/swift.yml
+++ b/.github/workflows/swift.yml
@@ -1,36 +1,87 @@
-# This is a basic workflow to help you get started with Actions
+name: BH Unit Test Workflow
 
-name: CI
-
-# Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the develop branch
-  push:
-    branches: [ develop ]
   pull_request:
-    branches: [ develop ]
+    branches:
+      - develop
+    types:
+      - opened
+      - synchronize
+      - reopened
 
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
-
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
   build:
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
+    name: Unit Tests
+    runs-on: macOS-latest
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v2
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
+#      - name: Setup SSH Authentication (Swift Package Manager)
+#        uses: webfactory/ssh-agent@v0.4.1
+#        with:
+#            ssh-private-key: ${{ secrets.SWIFT_PACKAGE_MANAGER_DEPLOY_KEY }}
 
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+#      - name: Adding Known Hosts for SSH (Swift Package Manager)
+#        run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
+
+      - name: Clone Repository
+        uses: actions/checkout@v2
+        with:
+          submodules: true
+
+      - name: Select Xcode
+        run: sudo xcode-select -switch /Applications/Xcode_12.2.app && /usr/bin/xcodebuild -version
+
+      - uses: actions/cache@v2
+        with:
+          path: Pods
+          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
+          restore-keys: |
+                       ${{ runner.os }}-pods-
+
+      - name: Pod Install
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+             cd BellaHealth
+             pod setup
+             pod install #--repo-update
+
+      - name: Execute Unit Tests
+        id: unitTest
+        continue-on-error: true
+        run: |
+             cd BellaHealth
+             xcodebuild test -scheme BellaHealth_Enterprise_Stage -workspace BellaHealth.xcworkspace -destination 'platform=iOS Simulator,OS=14.2,name=iPhone 12 Pro Max' clean test
+             echo "::set-output name=result::$?"
+             if [[ $? == 0 ]]; then
+             echo "Success"
+               else
+             echo "Failed"
+             fi
+             #swift test --enable-test-discovery
+
+#&& exit ${PIPESTATUS[0]}
+
+      - name: Dump steps context
+        env:
+          STEPS_CONTEXT: ${{ toJson(steps) }}
+        run: echo "$STEPS_CONTEXT"
+
+      - name: OnSuccess
+        if: steps.unitTest.outcome == 'success'
+        run: exit 0
+
+
+      - name: OnFailure
+        if: steps.unitTest.outcome == 'failure'
+        run: exit 1
+
+     # - name: Final_success
+      #  if: steps.unitTest.outputs.status == 'success' && steps.unitTest.outputs.outcome == 'success' && steps.unitTest.outputs.conclusion == 'success'
+       # run: exit 0
+
+      #- name: Final_failure
+        #if: steps.unitTest.outputs.status == 'failure' && steps.unitTest.outputs.outcome == 'failure' && steps.unitTest.outputs.conclusion == 'failure'
+         #run: |
+            #steps.unitTest.outputs.setFailed(error: "Unit test failure")
+            #exit 1
+
+      
